cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    abc:
      email: abc@123.com
      logged_in: false
      name: abc
      password: $2b$12$PSSHTYJVqBa5Fws0N1ZBZeklX0tkvNbN1uYxUTE6MtSPIlvvGBDuS
    ig-rpf-nfr:
      email: ccmfm@nfr.railnet.gov.in
      logged_in: false
      name: IG North East Frontier Railway
      password: $2b$12$.0N5ng/Rznn0zApK45VNrO.f/CB2BbNJzZrCw4BJauTPOANBSUXsm
    p8gh-u7ra-b2g8-uslj:
      email: siddarthbaruah39@gmail.com
      logged_in: false
      name: superUser
      password: $2b$12$/wVQTku.LrjoHMaZkQOpFOnQrDzdAAxJv/oDNIYPe3PMBQRuLUE4G
    sid:
      email: siddarthbaruah39@gmail.com
      failed_login_attempts: 1
      logged_in: false
      name: Sid
      password: $2b$12$E3qF.vKCRSa4MDnoI8kcxeiHUf8vTr4XuEUsoP2nAY1Qy4GdvqFka
preauthorized:
  emails:
  - siddarthbaruah39@gmail.com
